[build.env]
passthrough = [
    "BUILD_DIR",
    "CARGO_PROFILE_RELEASE_OPT_LEVEL",
    "RUST_BACKTRACE",
    "RUST_LOG",
    "RUSTFLAGS",
]

[target.x86_64-unknown-linux-musl]

[target.aarch64-unknown-linux-musl]

[target.x86_64-apple-darwin]
runner = "native"

[target.aarch64-apple-darwin]
runner = "native"