[build.env]
passthrough = [
    "BUILD_DIR",
    "CARGO_PROFILE_RELEASE_OPT_LEVEL",
    "RUST_BACKTRACE",
    "RUST_LOG",
    "RUSTFLAGS",
]

[target.x86_64-unknown-linux-musl]
zig = true

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-lm", "target-feature=+crt-static"
]

[target.aarch64-unknown-linux-musl]
zig = true

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-lm", "target-feature=+crt-static"
]

[target.x86_64-apple-darwin]
runner = "native"

[target.aarch64-apple-darwin]
runner = "native"