[build.env]
passthrough = [
    "BUILD_DIR",
    "CARGO_PROFILE_RELEASE_OPT_LEVEL",
    "RUST_BACKTRACE",
    "RUST_LOG",
    "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS",
]

[target.x86_64-unknown-linux-musl]
zig = { enable = true }

[target.aarch64-unknown-linux-musl]
zig = { enable = true }

[target.x86_64-apple-darwin]
runner = "native"

[target.aarch64-apple-darwin]
runner = "native"